/// Encrypted, persisted storage for the Supabase auth session (issue #347).
///
/// Ports `flutter_app/lib/platform/session/secure_session_storage.dart` to
/// this app. Read that file's comments first — this module exists for the
/// same reason: never leave a signed-in user's access/refresh tokens sitting
/// in plaintext on disk.
///
/// ## Why this isn't just "use `expo-secure-store` directly", like Flutter does
///
/// `flutter_secure_storage` writes straight to the OS Keychain/Keystore with
/// no practical size limit, so the Flutter client just persists the whole
/// session JSON there. `expo-secure-store`'s values are capped at roughly
/// 2 KB (Android backs it with `EncryptedSharedPreferences`, which rejects
/// larger entries), and a Supabase `Session` — access token (JWT) + refresh
/// token + the full `user` object (identities, `app_metadata`,
/// `user_metadata`, timestamps, ...) — comfortably exceeds that once an app
/// adds a few custom profile fields to `user_metadata`. Storing it raw in
/// `expo-secure-store` would work today and fail unpredictably later.
///
/// So this module uses the pattern the issue calls for: the bulk, size-
/// unbounded data lives in `@react-native-async-storage/async-storage`
/// (otherwise plaintext, local-only storage), but only ever as the output of
/// AES-256-GCM authenticated encryption. The one thing that actually has to
/// stay inside platform secure storage — the symmetric key — is small
/// (44 base64 chars for a 256-bit key) and comfortably fits in
/// `expo-secure-store`. Without that key, the AsyncStorage blob is useless;
/// losing or clearing secure storage (e.g. the user clears app data) simply
/// signs the user out, the same failure mode Flutter's `LocalStorage`
/// contract already has if the Keychain/Keystore entry disappears.
///
/// The encryption itself is `expo-crypto`'s native `aesEncryptAsync` /
/// `aesDecryptAsync` (AES-GCM backed by CryptoKit on Apple, Android Keystore
/// crypto providers on Android, and SubtleCrypto on web) — not a hand-rolled
/// cipher. A fresh random nonce is generated by the native implementation on
/// every single encrypt call (we never manage or reuse nonces ourselves),
/// and the authentication tag means a corrupted or tampered entry fails to
/// decrypt instead of silently returning garbage.
///
/// ## No legacy-plaintext migration (unlike Flutter's issue #7 / #179)
///
/// `secure_session_storage_test.dart`'s `initialize()` group exists because
/// an earlier Flutter release used supabase_flutter's own plaintext
/// `SharedPreferencesLocalStorage` before switching to secure storage, so a
/// migration path (and legacy-key deletion) was needed. There is no RN
/// equivalent: this is the very first time this app's Supabase client is
/// configured with any `auth.storage` at all (see
/// `src/platform/supabase/client.ts`), and absent that option
/// `@supabase/supabase-js` falls back to a pure in-memory store on React
/// Native (there is no `globalThis.localStorage` to use, unlike on web) — see
/// `memoryLocalStorageAdapter` in `@supabase/auth-js`. No prior build of this
/// app could have persisted a plaintext session anywhere on disk, so there is
/// no legacy key to read, migrate, or delete. If that ever changes (e.g. a
/// future refactor ships without a custom `storage` for a release), this
/// module would need a migration step analogous to Flutter's; nothing here
/// currently needs one.
///
/// ## Shape differences from Flutter's `LocalStorage`
///
/// Flutter's `LocalStorage` contract is a single named slot
/// (`hasAccessToken` / `accessToken` / `persistSession` /
/// `removePersistedSession`) because supabase_flutter owns exactly one
/// session value. `@supabase/supabase-js`'s `SupportedStorage` contract is a
/// generic string-keyed store (`getItem` / `setItem` / `removeItem`)
/// instead: besides the session itself, the PKCE auth flow persists one-off
/// code verifiers under adjacent keys through the same storage instance (see
/// `storePKCEVerifier` in `@supabase/auth-js`'s `helpers.ts`). This module
/// mirrors that generic shape so every key the client ever uses gets the same
/// encrypted-at-rest treatment, not just the main session slot.
import {
  AESEncryptionKey,
  AESKeySize,
  AESSealedData,
  aesDecryptAsync,
  aesEncryptAsync,
} from 'expo-crypto';
import * as SecureStore from 'expo-secure-store';
import AsyncStorage from '@react-native-async-storage/async-storage';

/**
 * The `@supabase/supabase-js` `SupportedStorage` contract (see
 * `@supabase/auth-js`'s `lib/types.ts`), spelled out locally so this module
 * doesn't need a direct type import from deep inside the auth package.
 */
export interface KeyValueStorage {
  getItem(key: string): Promise<string | null>;
  setItem(key: string, value: string): Promise<void>;
  removeItem(key: string): Promise<void>;
}

/**
 * The slice of `expo-secure-store`'s API this module depends on. Injectable
 * so a future Jest test (issue #349) can supply an in-memory fake instead of
 * the real native module — mirrors how
 * `secure_session_storage_test.dart` swaps in
 * `FlutterSecureStorage.setMockInitialValues` / a fake `LegacySessionStore`.
 */
export interface SecureKeyValueStore {
  getItemAsync(key: string): Promise<string | null>;
  setItemAsync(key: string, value: string): Promise<void>;
  deleteItemAsync(key: string): Promise<void>;
}

/** The slice of `@react-native-async-storage/async-storage`'s API this module depends on. */
export interface BulkKeyValueStore {
  getItem(key: string): Promise<string | null>;
  setItem(key: string, value: string): Promise<void>;
  removeItem(key: string): Promise<void>;
}

/**
 * The symmetric-encryption operations this module needs, factored out so
 * storage-logic tests can inject a deterministic fake cipher instead of
 * requiring a real native `expo-crypto` binding (which Jest, run on Node,
 * cannot provide).
 */
export interface SessionCipher {
  /**
   * Encrypts UTF-8 plaintext bytes, returning one storable string that
   * embeds everything needed to decrypt it later (nonce + ciphertext + AES-GCM
   * authentication tag).
   */
  encrypt(plaintext: Uint8Array): Promise<string>;
  /**
   * Reverses {@link encrypt}. Rejects if `sealed` is malformed or the
   * authentication tag doesn't verify (corrupted or tampered data).
   */
  decrypt(sealed: string): Promise<Uint8Array>;
}

const ENCRYPTION_KEY_SECURE_STORE_KEY = 'supabase.session.encryptionKey';
const ASYNC_STORAGE_KEY_PREFIX = 'supabase.session.';

const defaultSecureKeyValueStore: SecureKeyValueStore = {
  getItemAsync: (key) => SecureStore.getItemAsync(key),
  setItemAsync: (key, value) => SecureStore.setItemAsync(key, value),
  deleteItemAsync: (key) => SecureStore.deleteItemAsync(key),
};

const defaultBulkKeyValueStore: BulkKeyValueStore = {
  getItem: (key) => AsyncStorage.getItem(key),
  setItem: (key, value) => AsyncStorage.setItem(key, value),
  removeItem: (key) => AsyncStorage.removeItem(key),
};

/**
 * Builds a {@link SessionCipher} backed by `expo-crypto`'s native AES-GCM
 * implementation. The AES-256 key is generated once (first call ever) and
 * persisted in `secureKeyValueStore`; every later call re-imports it from
 * there, so the key — and therefore every previously-encrypted entry — stays
 * valid across app restarts.
 */
export function createExpoAesSessionCipher(
  secureKeyValueStore: SecureKeyValueStore = defaultSecureKeyValueStore,
): SessionCipher {
  // Memoized so concurrent first-ever calls can't each generate (and
  // persist) a *different* key, which would leave whichever one lost the
  // race undecryptable, and so every call after the first reuses the same
  // key without re-reading secure storage each time.
  let keyPromise: Promise<AESEncryptionKey> | null = null;

  function getOrCreateKey(): Promise<AESEncryptionKey> {
    if (keyPromise == null) {
      keyPromise = (async () => {
        const existing = await secureKeyValueStore.getItemAsync(ENCRYPTION_KEY_SECURE_STORE_KEY);
        if (existing != null) {
          return AESEncryptionKey.import(existing, 'base64');
        }

        const generated = await AESEncryptionKey.generate(AESKeySize.AES256);
        const encoded = await generated.encoded('base64');
        await secureKeyValueStore.setItemAsync(ENCRYPTION_KEY_SECURE_STORE_KEY, encoded);
        return generated;
      })();

      // A transient failure (e.g. one flaky SecureStore write) shouldn't
      // permanently wedge every future read/write behind the same rejected
      // promise — let the next call try again from scratch.
      keyPromise.catch(() => {
        keyPromise = null;
      });
    }
    return keyPromise;
  }

  return {
    async encrypt(plaintext) {
      const key = await getOrCreateKey();
      const sealed = await aesEncryptAsync(plaintext, key);
      return sealed.combined('base64');
    },
    async decrypt(sealed) {
      const key = await getOrCreateKey();
      const sealedData = AESSealedData.fromCombined(sealed);
      return aesDecryptAsync(sealedData, key, { output: 'bytes' });
    },
  };
}

/**
 * `SupportedStorage` implementation that encrypts every value with
 * {@link SessionCipher} before it reaches `bulkKeyValueStore`
 * (`@react-native-async-storage/async-storage` by default). Pass this
 * directly as `auth.storage` to `createClient` (see
 * `src/platform/supabase/client.ts`).
 */
export class EncryptedAsyncStorage implements KeyValueStorage {
  private readonly bulkKeyValueStore: BulkKeyValueStore;
  private readonly cipher: SessionCipher;

  constructor(options: { bulkKeyValueStore?: BulkKeyValueStore; cipher?: SessionCipher } = {}) {
    this.bulkKeyValueStore = options.bulkKeyValueStore ?? defaultBulkKeyValueStore;
    this.cipher = options.cipher ?? createExpoAesSessionCipher();
  }

  async getItem(key: string): Promise<string | null> {
    const sealed = await this.bulkKeyValueStore.getItem(namespacedKey(key));
    if (sealed == null) {
      return null;
    }
    try {
      const plaintext = await this.cipher.decrypt(sealed);
      return utf8Decode(plaintext);
    } catch {
      // A value that fails to decrypt (corrupted, tampered, or the
      // encryption key is gone/rotated) is indistinguishable from "no
      // session" as far as the auth client is concerned — fail safe into
      // signed-out rather than throwing out of a storage read, the same
      // fail-safe posture `supabase_flutter`'s own storage takes on an
      // unreadable value.
      return null;
    }
  }

  async setItem(key: string, value: string): Promise<void> {
    const sealed = await this.cipher.encrypt(utf8Encode(value));
    await this.bulkKeyValueStore.setItem(namespacedKey(key), sealed);
  }

  async removeItem(key: string): Promise<void> {
    await this.bulkKeyValueStore.removeItem(namespacedKey(key));
  }
}

function namespacedKey(key: string): string {
  return `${ASYNC_STORAGE_KEY_PREFIX}${key}`;
}

/**
 * Encodes `value` as UTF-8 bytes. Hand-written instead of relying on a
 * global `TextEncoder` because React Native/Hermes does not guarantee one is
 * present (see this file's imports — no polyfill for it is installed here),
 * and instead of the classic `unescape(encodeURIComponent(...))` trick to
 * avoid depending on those (deprecated) globals either. Plain encoding, not
 * encryption — safe to hand-roll, unlike the AES above.
 */
export function utf8Encode(value: string): Uint8Array {
  const bytes: number[] = [];
  for (let i = 0; i < value.length; i += 1) {
    let codePoint = value.codePointAt(i);
    if (codePoint === undefined) {
      continue;
    }
    if (codePoint > 0xffff) {
      // Surrogate pair: consumes two UTF-16 code units.
      i += 1;
    }
    if (codePoint < 0x80) {
      bytes.push(codePoint);
    } else if (codePoint < 0x800) {
      bytes.push(0xc0 | (codePoint >> 6), 0x80 | (codePoint & 0x3f));
    } else if (codePoint < 0x10000) {
      bytes.push(
        0xe0 | (codePoint >> 12),
        0x80 | ((codePoint >> 6) & 0x3f),
        0x80 | (codePoint & 0x3f),
      );
    } else {
      bytes.push(
        0xf0 | (codePoint >> 18),
        0x80 | ((codePoint >> 12) & 0x3f),
        0x80 | ((codePoint >> 6) & 0x3f),
        0x80 | (codePoint & 0x3f),
      );
    }
  }
  return Uint8Array.from(bytes);
}

/** Reverses {@link utf8Encode}. */
export function utf8Decode(bytes: Uint8Array): string {
  let result = '';
  let i = 0;
  while (i < bytes.length) {
    const byte1 = bytes[i];
    if (byte1 < 0x80) {
      result += String.fromCharCode(byte1);
      i += 1;
    } else if ((byte1 & 0xe0) === 0xc0) {
      const byte2 = bytes[i + 1];
      result += String.fromCharCode(((byte1 & 0x1f) << 6) | (byte2 & 0x3f));
      i += 2;
    } else if ((byte1 & 0xf0) === 0xe0) {
      const byte2 = bytes[i + 1];
      const byte3 = bytes[i + 2];
      result += String.fromCharCode(((byte1 & 0x0f) << 12) | ((byte2 & 0x3f) << 6) | (byte3 & 0x3f));
      i += 3;
    } else {
      const byte2 = bytes[i + 1];
      const byte3 = bytes[i + 2];
      const byte4 = bytes[i + 3];
      const codePoint =
        ((byte1 & 0x07) << 18) | ((byte2 & 0x3f) << 12) | ((byte3 & 0x3f) << 6) | (byte4 & 0x3f);
      result += String.fromCodePoint(codePoint);
      i += 4;
    }
  }
  return result;
}
